### ISSUE TITLE
feat: Automatically hide tags of mass-reported players

### ISSUE THREAD

**Issue by Kallecrafter** [Global-Tags/LabyAddon#73]
Bei 10 Reports in unter 5 Minuten wird ein GlobalTag automatisch für jeden Spieler außer sich selbst Ausgeschaltet. Und wenn ein Teammitglied das ganze Sieht, und es ein fehlreport ist, kann es wieder freigeschaltet werden. Nach 15 Minuten wird ein Globaler Report Automatisch wieder Freigeschaltet.
Spieler die Oft ohne Grund Gemeldet werden, weil Troller das dann gerne Ausnutzen würden, können auf eine sogenannte Weiße liste gesetzt werden, was die Spieler ermöglicht nicht mehr auto geblockt zu werden, Partner und Teammitglieder sind ebenfalls direkt auf der Weißen Liste, Partner müssten wenn dann schon direkt von Teammitglieder geblockt werden.

**Comment by RappyTV** [comment]
I probably won't implement something like this because it would just be open a way to abuse the report feature. There is not even a player with over 10 reports until now so I don't think it would even be used anytime soon. If the project grows bigger I can think about implementing something like this again.
